version: '3'

services:

  ankete_db:

    image: postgres
    ports: 
      - "54320:5432"
    container_name: ankete_db

  ankete:

    build: .
    container_name: ankete
    command: gunicorn -b 0.0.0.0:8000 ankete.wsgi
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - ankete_db