# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ankete', '0002_auto_20180309_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
