# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankete', '0003_auto_20180309_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiansw',
            field=models.BooleanField(default=False),
        ),
    ]
