# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankete', '0004_auto_20180309_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
