# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ankete', '0005_auto_20180309_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
